#!/bin/bash


# Copyright (c) 2025, Bryan Enneking
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
# 
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


show_help() {
    echo "Usage: osc <address> <type tags> <argument 1> [<argument 2>...]"
    echo "Send an Open Sound Control (OSC) message via UDP"
    echo
    echo "  <address>    The OSC address string (e.g. /path/method)"
    echo "  <type tags>  Character(s) indicating the types of <argument> in order"
    echo "               's' for strings, 'i' for integers, and 'f' for floats."
    echo "  <argument>   Argument(s) corresponding to the types defined by <type tags>"
    echo "               **Note: float arguments must be specified in hexidecimal**"
    echo
    echo "Example 1: osc /ch/29/config/name s \"Bass Amp\""
    echo "  Sends an OSC message with a single string to set the name of channel 29"
    echo
    echo "Example 2: osc /dca/4/fader f 3f400000"
    echo "  Sends an OSC message with a single float to set the DCA 4 fader level"
    echo
    echo "Example 3: osc /channel/75/config ssif \"Cello 5\" ON 13 00000000"
    echo "  Sends an OSC message with two strings, an integer, and a float argument"
    echo
    echo "The variables OSC_IP and OSC_PORT must be set before using Bash OSC."
    echo "  export OSC_IP=169.254.246.252"
    echo "  export OSC_PORT=10023"
    echo
}

send_osc_message() {
    local osc_message=""
    local tag_pos=0;
    local type_tags="ss$2"   # prepend tags for address and tags strings
    local arguments=("$@")   # treat address, tags, and OSC arguments the same
    arguments[1]=",$2"       # OSC tags string must start with a ','
    for arg in "${arguments[@]}"; do
        local current_tag=${type_tags:tag_pos:1}
        case $current_tag in
            s) osc_message+="$arg\0"
               local padding=$(((4 - ((${#arg} + 1) % 4)) % 4))
               for ((i = 0; i < padding; i++)); do
                   osc_message+='\0'
               done;;
            i) printf -v arg "%08X" "$arg";&  # convert to hex and fall through
            f) osc_message+="\x${arg:0:2}\x${arg:2:2}\x${arg:4:2}\x${arg:6:2}";;
        esac
        ((tag_pos++));
    done
    echo -ne "$osc_message" > /dev/udp/$OSC_IP/$OSC_PORT
}

# handle direct invocations
if [[ "$0" == "${BASH_SOURCE[0]}" ]]; then
    if [[ $# -lt 3 ]]; then
        show_help
    else
        send_osc_message "$@"
    fi
fi
